### ISSUE TITLE
publish to friends package

### ISSUE THREAD

**Issue by Flet** [moose-team/friends-cli#1]
Hello!

Is it possible for someone with access to publish this to https://www.npmjs.com/package/friends?

**Comment by ungoldman** [comment]
I tested it locally, added a missing dep (`cat-names`), threw in standard and a change log for good measure, and published `v1.0.0-alpha.1` to npm. I also gave you access to the `friends` package on npm so you should be able to do as you wish now :)

**Comment by Flet** [comment]
Excellent! Thanks @ungoldman :)
